### ISSUE TITLE
HTTPS in <url> tag

### ISSUE THREAD

**Issue by matheussouza9** [xiph/ezstream#10]
I'm using Icecast with SSL enabled, but ezstream doesn't allow a https url in <url> tag.

Error message:
```
ezstream: Error: Invalid <url>: Not an HTTP address
Must be of the form ``http://server:port/mountpoint''
```

**Comment by mgrimm** [comment]
Hi, the current development version (develop branch) is in good shape and supports that, if you build it against an TLS-enabled libshout.
Your test results would be very interesting, please report back on how this works for you.

**Comment by matheussouza9** [comment]
Ok, I'll try it. But the code specifically looks for `"http://"` in `url` parameter.
https://github.com/xiph/ezstream/blob/develop/src/ezstream-cfgmigrate.c#L124

**Comment by mgrimm** [comment]
That is from the configuration migration tool from legacy 0.x to the eventually upcoming 1.0.
________________________________

Sophos Technology GmbH, Amalienbadstr. 41/Bau 52, D-76227 Karlsruhe, Deutschland
Tel +49 (0)721 25516 0 Fax +49 (0)721 25516 200 E-Mail info@sophos.de www.sophos.de
Sitz der Gesellschaft: Karlsruhe, Amtsgericht Mannheim HRB 712658
Geschäftsführer: Nicholas Bray, Pino von Kienlin, Jennifer Onslow.
Sophos Technology GmbH, Gustav-Stresemann-Ring 1, 65189 Wiesbaden, Deutschland
Tel +49 (0) 611 5858-0 Fax +49 (0) 611 5858-1042 E-Mail info@sophos.de www.sophos.de
Sitz der Gesellschaft: Karlsruhe, Amtsgericht Mannheim HRB 712658
Geschäftsführer: Nicholas Bray, Pino von Kienlin, Jennifer Onslow

**Comment by mgrimm** [comment]
@matheussouza9 did you have any luck trying TLS with develop?
