### ISSUE TITLE
Feature Request: ability to pause stream

### ISSUE THREAD

**Issue by simon1tan** [xiph/ezstream#13]
Hi. Can we add an ability to pause a stream and allow it to play again? If that's too difficult, can we set the stream to play starting at a certain time? That would be awesome.

**Comment by mgrimm** [comment]
Try to solve this with Icecast fallback-mount/-override settings and cron(1)/at(1) to (re)start a stream at the right time, or a continuous live stream using different tools altogether. Ezstream cannot generate content on its own; it merely pipes existing content through decoders, encoders, and libshout for sending the stream to Icecast.

When you want silence as the fallback stream, make sure to let it contain pleasant low-volume noise (artificially done by modern telephones, and naturally done by legacy analog telephones). The intent is to keep the VBR stream bitrate high enough to ensure that client buffers don't fall back in time too much as they fill up with many minutes of absolute silence. It is also more pleasing to listeners on the fallback mount, as they get an intimation of "still being connected" acoustically as well.

Hope that helps!
