### ISSUE TITLE
Descriptive error when using legacy config

### ISSUE THREAD

**Issue by zacs** [xiph/ezstream#24]
I spent an embarrassing amount of time discovering that my config was invalid. There are 10+ years of online articles/forum posts (some as recent as this year) showing examples of the pre-v1 config. It would be awesome if ezstream could detect an old style config and let the user know about the breaking change in the v1 config. 

Thanks a ton for this tool. It works amazingly well.

**Comment by mgrimm** [comment]
After thinking more about this, I really don't want to teach ezstream v1 about v0 configs (it would need some heuristics to do this detection). In case there is ever a need for a v2 (which implies another incompatible configuration change), I will revisit this by considering an optional version number in v1 and a mandatory one in v2. Until then, I'm closing this as "won't fix". Thanks for the report!
