### ISSUE TITLE
Resume on restart?

### ISSUE THREAD

**Issue by shaksp** [xiph/ezstream#27]
Hi,

Is there any way to make ezstream continue a playlist from the file or position it was in before it was shut down?
I have a very long playlist going to a Icecast server and ideally wan't it to continue on reboot or restart of the ezstream application.

Kind Regards,

**Comment by mgrimm** [comment]
Hi,

This requires scripting with a playlist program that keeps state independently. You can take a look at examples/playlist-logger.sh and see, if that works sufficiently well with your playlist.

-Moritz
