### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by finnie2006** [xiph/ezstream#29]
Mar 10 10:58:10 raspberrypi ezstream[9679]: WARNING: libsndfile may ignore -r and perform fseek's on the input.
Mar 10 10:58:10 raspberrypi ezstream[9679]: Compile without libsndfile if this is a problem.
Mar 10 10:58:10 raspberrypi ezstream[9679]: ezstream: Streaming ``Milky Chance - Stolen Dance''
Mar 10 10:58:10 raspberrypi ezstream[9679]: /home/pi/Desktop/Geniaal/073: No such file or directory
Mar 10 10:58:10 raspberrypi ezstream[9679]: The: No such file or directory
Mar 10 10:58:10 raspberrypi ezstream[9679]: Weeknd: No such file or directory
Mar 10 10:58:10 raspberrypi ezstream[9679]: I: No such file or directory
Mar 10 10:58:10 raspberrypi ezstream[9679]: Feel: No such file or directory
Mar 10 10:58:10 raspberrypi ezstream[9679]: It: No such file or directory
Mar 10 10:58:10 raspberrypi ezstream[9679]: Coming.mp3: No such file or directory
Mar 10 10:58:10 raspberrypi ezstream[9679]: WARNING: libsndfile may ignore -r and perform fseek's on the input.
Mar 10 10:58:10 raspberrypi ezstream[9679]: Compile without libsndfile if this is a problem.

**Comment by mgrimm** [comment]
This report does not contain enough information to verify, if there is a problem with ezstream. Please let me know, if this is still an issue and how to reproduce it.

**Comment by finnie2006** [comment]
Issue was opened 1 year ago.... moved to other software now

**Comment by mgrimm** [comment]
OK, thanks for the response!
