### ISSUE TITLE
I can't stream

### ISSUE THREAD

**Issue by zygmund2000** [xiph/ezstream#3]
Hi,

Can you make working .xml example to stream from soundcard input or from raw data stdin to server?
At the moment I don't understand how to do that.

Regards

**Comment by TETYYS** [comment]
`examples/ezstream_stdin_vorbis.xml` has raw data stdin example.

**Comment by zygmund2000** [comment]
I can't find this file.

**Comment by TETYYS** [comment]
https://github.com/xiph/ezstream/blob/master/examples/ezstream_stdin_vorbis.xml

**Comment by zygmund2000** [comment]
It's really strange, today tried ctl+f to find file in this folder and didn't exist.

**Comment by TETYYS** [comment]
develop branch doesn't have some example xmls for some reason

**Comment by mgrimm** [comment]
Added a minimal example for streaming Vorbis from standard input as-is.
