### ISSUE TITLE
Regression in playlist filepath handling?

### ISSUE THREAD

**Issue by pe1rrr** [xiph/ezstream#34]
Due to a rebuild of a ezstream server used to run a looped announcement as a fallback  with icecast, I ran across some issues that are show stoppers in the current develop branch which seem to have crept in somewhere between version 0.5.6 and 0.6.0 and are still present in the latest git pull.

My first stumbling block was realising the new ezstream had been migrated to proper XML and the config file compiled fine.

The issue arises when presenting the intake with a full path to a playlist.txt format that contains a file also referenced via full path.

When starting the stream up ezstream goes into a loop:

```
Assuming raw pcm input file
LAME 3.100 32bits (http://lame.sf.net)
Autoconverting from stereo to mono. Setting encoding to mono mode.
Resampling:  input 22.05 kHz  output 8 kHz
Using polyphase lowpass filter, transition band:  3000 Hz -  3097 Hz
Encoding <stdin> to <stdout>
Encoding as 8 kHz single-ch MPEG-2.5 Layer III (16x)   8 kbps qval=3
ezstream: Streaming `` EHGR Announcement''
MPEG Audio Decoder 0.15.2 (beta) - Copyright (C) 2000-2004 Robert Leslie et al.
'/home/xxx/radio/ehgr-loop.mp3': No such file or directory
WARNING: libsndfile may ignore -r and perform fseek's on the input.
Compile without libsndfile if this is a problem.
```

This 'No such file or directory' error does not occur on the build of ezstream 0.5.6 on the same system. 

Grabbing the source for 0.5.6 from the archives on xiph I easily built and got the thing working as it used to on the old system that I am migrating from. I had hoped that it would have worked with the new version but alas it is apparently broken?

I compiled 0.6.1 as well and tested it with the same results.

This is what is looks like when it is working on v0.5.6
```

xxx@xxx:~/radio $ ./ehgr-announcer.sh 
ezstream: Connected to http://localhost:9090/ehgr-fallback-fallback
ezstream: Streaming ``EHGR Announcement''
MPEG Audio Decoder 0.15.2 (beta) - Copyright (C) 2000-2004 Robert Leslie et al.
          Title: EHGR Announcement
         Artist: xxx
           Year: 2020
          Genre: Speech
1165 frames decoded (0:00:30.4), -6.8 dB peak amplitude, 0 clipped samples
WARNING: libsndfile may ignore -r and perform fseek's on the input.
Compile without libsndfile if this is a problem.
Assuming raw pcm input file
LAME 3.100 32bits (http://lame.sf.net)
Autoconverting from stereo to mono. Setting encoding to mono mode.
Resampling:  input 22.05 kHz  output 8 kHz
Using polyphase lowpass filter, transition band:  3000 Hz -  3097 Hz
Encoding <stdin> to <stdout>
Encoding as 8 kHz single-ch MPEG-2.5 Layer III (16x)   8 kbps qval=3
```

**Comment by mgrimm** [comment]
@pe1rrr, can you please share some additional information on how to reproduce this (e.g. playlist and config files). The scenario you describe sounds pretty much exactly how I stream playlists, and it works for me.

**Comment by pe1rrr** [comment]
> @pe1rrr, can you please share some additional information on how to reproduce this (e.g. playlist and config files). The scenario you describe sounds pretty much exactly how I stream playlists, and it works for me.

```
<ezstream>
    <url>http://localhost:9090/ehgr-fallback-fallback</url>
    <sourcepassword>xxxxxx</sourcepassword>
    <format>MP3</format>
    <shuffle>0</shuffle>
    <filename>/home/xxx/radio/ehgr-ezstream.txt</filename>
    <stream_once>0</stream_once>
    <svrinfoname>EHGR ATC Fallback Fallback Stream</svrinfoname>
    <svrinfourl>http://xxxxxx.xxxxxx</svrinfourl>
    <svrinfogenre>ATC</svrinfogenre>
    <svrinfodescription>...</svrinfodescription>
    <svrinfopublic>1</svrinfopublic>

    <reencode>
        <enable>1</enable>
        <encdec>
            <format>FLAC</format>
            <match>.flac</match>
            <decode>flac -s -d --force-raw-format --sign=signed --endian=little -o - "@T@"</decode>
        </encdec>
        <encdec>
            <format>MP3</format>
            <match>.mp3</match>
            <!-- Note: madplay uses host byte order for raw samples. -->
            <decode>madplay -b 16 -R 22050 -S -o raw:- "@T@"</decode>
            <encode>lame -a --preset cbr 8 -r -s 22050 --bitwidth 16 - -</encode>
        </encdec>
    </reencode>
</ezstream>
```

Playlist:

```
/home/xxx/radio/ehgr-loop.mp3
```

**Comment by mgrimm** [comment]
Apologies for the delays, it took a while for me to be able to look further into this.
Ezstream 0.6.0 fixes a shell injection vulnerability and as a consequence you need to remove those quotation marks around your `@T@`s and `@M@`s. See https://github.com/xiph/ezstream/blob/develop/NEWS#L77 for reference.
