### ISSUE TITLE
Add timestamp to log message

### ISSUE THREAD

**Issue by tyctor** [xiph/ezstream#39]
Hi 

it would be nice to have configurable log message
for example add timestamp at beggining of line would be very helpful in my case
and also filename which trying to play

this is my error, it is not very useful to read

```
ezstream[631405]: stream: default: send: 77.99.223.221: error -4: Socket error
ezstream[631405]: shout_set_metadata: No error
ezstream[631405]: stream: default: send: 77.99.223.221: error -4: Socket error
ezstream[631405]: stream: default: send: 77.99.223.221: error -4: Socket error
ezstream[631405]: shout_set_metadata: No error
ezstream[631405]: stream: default: send: 77.99.223.221: error -4: Socket error
ezstream[631405]: stream: default: send: 77.99.223.221: error -4: Socket error
ezstream[631405]: shout_set_metadata: No error
ezstream[631405]: stream: default: send: 77.99.223.221: error -4: Socket error
```

**Comment by mgrimm** [comment]
Ezstream uses syslog for logging messages, so by default you have all messages (with timestamp) in /var/log/syslog or /var/log/messages (depending on your system). You can configure your system's syslog to log messages from ezstream into dedicated files, autorotate them, send them off to central logging servers, etc. Please refer to your system logger documentation for details.

I will look into adding some context to messages related to errors while sending.

**Comment by mgrimm** [comment]
There is no additional context available at that point, but you can increase log verbosity using -v up to three times. By default, only warnings and errors are logged. Using the option adds notice, informational, and debug messages respectively.
