### ISSUE TITLE
Error 'No such file or directory' is not valid

### ISSUE THREAD

**Issue by bodsch** [xiph/ezstream#4]
I installed version 0.6.0 today to play with an private icecast service.
I have large mp3 library with following namesyntax: 
```$artist/[$recordyear] - $recordtitle/$trackumber - $tracktitle```

the m3u file created with a fast find:
```find /media/sounds  -name "*.mp3" -print > /opt/icecast/latest/etc/test.m3u```

But, ezstream is not so happy and out the following error:
    `ezstream: "/media/sounds/alternativ/Lili Marlene/[2000] - Lili Marlene - The Best of Marlene Dietrich/12 - Near You.mp3": No such file or directory`

The File is present and the User has full right over there.

Now, i replace all spaces with underscore of the directorys and files und ezstream works fine.

Please change the Docu for this problem, **and** (my importend wish) the working of ezstream!

**Comment by TETYYS** [comment]
If you use reencode feature, try running ezstream with `-v -v` and there's a chance that you will see that your audio file name is passed to decoding/encoding command line in invalid format.

To fix this, try replacing these in https://github.com/xiph/ezstream/blob/e5e77520afa123eff622a0a6e3a288378010d65b/src/util.c

```diff
https://github.com/xiph/ezstream/blob/e5e77520afa123eff622a0a6e3a288378010d65b/src/util.c#L263
< 	*out_p++ = '\'';
---
> 	*out_p++ = '"';
https://github.com/xiph/ezstream/blob/e5e77520afa123eff622a0a6e3a288378010d65b/src/util.c#L267
< 		case '\'':
---
> 		case '"':
https://github.com/xiph/ezstream/blob/e5e77520afa123eff622a0a6e3a288378010d65b/src/util.c#L278
< 	*out_p++ = '\'';
---
> 	*out_p++ = '"';
```

but im not sure if this introduces any vulnerabilities so use at your own risk

**Comment by bodsch** [comment]
Hi TETTYS!

I've compiled just the deveolp branch with your patch above.
After needed changes (xml format) .. it works for me! :)

Thanks for your help
```
/var/tmp/ezstream/src/ezstream -v -v -c ./local.xml 
ezstream[16390]: ./local.xml: world readable
ezstream[16390]: default: TLS optional but not supported by libshout
ezstream[16390]: connected: http://127.0.0.1:8000/local.mp3
ezstream[16390]: streaming: Megaherz - Licht II (instrumental) (/srv/data/sound/[2002] - herzwerk 2/08 - licht 2.mp3)
ezstream[16390]: streaming: Megaherz - Spiel nicht (/srv/data/sound/[2002] - herzwerk 2/12 - spiel nicht.mp3)
```

**Comment by TETYYS** [comment]
Hmm, I'm using 0.6.0 so it could be that it was fixed propertly in develop.. Were you using develop version before?

**Comment by bodsch** [comment]
Version 0.6.0

**Comment by TETYYS** [comment]
Try using develop version of ezstream without a patch, maybe the issue was fixed. If not, then you can continue using 0.6.0 with the patch

**Comment by bodsch** [comment]
I'm currently under stress ... i will test it at this weekend

**Comment by mgrimm** [comment]
Seems to be working in develop; closing issue report as "invalid".
