### ISSUE TITLE
meta.sh example gives segmentation fault using example's data

### ISSUE THREAD

**Issue by JohnnyC1951** [xiph/ezstream#40]
V1.0.1
I changed every reference to fully qualified in the xml files and it still did the same.
Has this worked recently?
It loads and a few seconds later gives the seg fault with no other information.
Calling meta.sh on it's own gives the correct example metadata, from anywhere in the file system, so it seems it is inside ezstream

**Comment by mgrimm** [comment]
This is already fixed in 1.0.2.
