### ISSUE TITLE
Improve installation documentation

### ISSUE THREAD

**Issue by Abdull** [xiph/ezstream#5]
My environment: Ubuntu 16.04 LTS

file `README` mentions `INSTALL`. File `INSTALL` seems to be a generic GNU Project file, mentioning *autotools* and `./configure; make; make install`.

This was too abstract for someone like me who doesn't have knowledge of the *GNU Build System*. Also, I couldn't tell which git branch or git tag I should prefer for building.
 
Here are the steps I had to additionally do on a quite vanilla Ubuntu 16.04 machine:
```
sudo apt-get install autotools-dev automake autoconf libtools-bin check libshout3-dev libxml2 libtagc0-dev
autoreconf --install
./configure
make
sudo make
```
After that and since then, ezstream works well. Thank you very much!

**Comment by PodcastGGstar** [comment]
Hello, 

in the src/metadata.c the struct metadata struct and the struct ID3Tag do not match:
struct metadata {
    char    *filename;
    char    *string;
    char    *artist;
    char    *title;
    int     songLen;
    int     normalize;
    int     program;
};

struct ID3Tag {
    char tag[3];
    char trackName[30];
    char artistName[30];
    char albumName[30];
    char year[4];
    char comment[30];
    char genre;
};

the bottom struct has ID3Tag with album while metadata struct does not.  

Could you please look into changing the struct and adjusting the code to accommodate album in the metadata.

**Comment by mgrimm** [comment]
@Abdull: I won't put OS-dependent stuff into the docs unless absolutely necessary, but I have added the references to "check" and "autogen.sh", which is the current ezstream way of bootstrapping the build. Ezstream loosely follows the GitFlow branching model, so the thing to remember is that "develop" is the stable base for development. Other than that, being able to build stuff from source assumes "advanced user", whereas building stuff from source control assumes "advanced user + developer". I do not plan to add howto-style documentation to ezstream.

@PodcastGGstar: Someone else picked that up: https://github.com/xiph/ezstream/pull/9 (from @redswitchio)
