### ISSUE TITLE
Quotation marks around metadata

### ISSUE THREAD

**Issue by stimpy23** [xiph/ezstream#6]
After having updated to v0.6.0, I have quotation marks around all my metadata.
For example: **'**Moby**'** - **'**Go**'**

Excerpt from my ezstream.xml config:
```
<metadata_progname>/home/evostream/ezweb/np.php</metadata_progname>
<metadata_format>@s@ - @t@</metadata_format>
```
np.php is returning all data completely unquoted.

Is this me being stupid or is it a bug introduced by the quoting-fix in v0.6.0? And is this (re-)fixed already somehow backportable for me?

Cheers and thanks in advance,
  Philipp

**Comment by stimpy23** [comment]
Okay, I was able to workaround this issue by not using the <metadata_format> parameter at all..

**Comment by mgrimm** [comment]
This smells like a regression. Can you please attach (with both passwords and server hostnames, etc., redacted!) your configuration file, and some verbatim output from np.php, for easier reproduction. Thanks!

**Comment by stimpy23** [comment]
I'll have to recreate the situation locally since the original system is running productive, now.. I'll try to do so within the next few days...

**Comment by zefie** [comment]
Same issue, here is the output of my metadata script:
`Shawn Mendes - There's Nothing Holdin' Me Back`

Here is what it sends to Icecast:
`'Shawn Mendes - There\'s Nothing Holdin\' Me Back'`

Here is the config:
`<ezstream>
    <url>[redacted]</url>
    <sourcepassword>[redacted]</sourcepassword>
    <filename>stdin</filename>
    <format>VORBIS</format>
    <stream_once>1</stream_once>
    <svrinfoname>Radio</svrinfoname>
    <svrinfourl></svrinfourl>
    <svrinfogenre></svrinfogenre>
    <svrinfodescription>This is a stream description</svrinfodescription>
    <svrinfobitrate>256</svrinfobitrate>
    <svrinfoquality>2.0</svrinfoquality>
    <svrinfochannels>2</svrinfochannels>
    <svrinfosamplerate>44100</svrinfosamplerate>
    <svrinfopublic>0</svrinfopublic>
    <metadata_progname>/home/zefie/.config/hdradio_meta.sh</metadata_progname>
    <metadata_format>@s@</metadata_format>
</ezstream>`

Issue op explains can be repo'd by chaning metadata_format from `@s@` to `@a@ - @t@`
Can confirm OP's method of removing (or commenting out) the metadata_format param fixes it.

As for the stdin in the config, I'm sending an pre-encoded vorbis stream from ffmpeg to ezstream.

**Comment by mgrimm** [comment]
This particular issue should now be fixed in develop. There's still one or two issues in the quoting area that will be fixed at a later time.

For now, if someone runs into problems with some files, avoid running de-/encoder programs with metadata in the command line altogether.
