### ISSUE TITLE
Parsing out ID3v1 Metadata 

### ISSUE THREAD

**Issue by PodcastGGstar** [xiph/ezstream#7]
Hello,

in the src/metadata.c the struct metadata struct and the struct ID3Tag do not match:
struct metadata {
char *filename;
char *string;
char *artist;
char *title;
int songLen;
int normalize;
int program;
};

struct ID3Tag {
char tag[3];
char trackName[30];
char artistName[30];
char albumName[30];
char year[4];
char comment[30];
char genre;
};

the bottom struct has ID3Tag with album while metadata struct does not.

Could you please look into changing the struct and adjusting the code to accommodate album in the metadata.

**Comment by mgrimm** [comment]
https://github.com/xiph/ezstream/pull/9
