### ISSUE TITLE
Multiple Playlists/Mounts from a single XML config file?

### ISSUE THREAD

**Issue by ghost** [xiph/ezstream#8]
I have three playlists I wish to serve up to my icecast server, but can't figure out how to do it (short of having 3x totally seperate config files, 3x playlists, 3xstartup scripts, 3xPIDs).

Is this possible?  If not, a suggestion, re-arrange the nesting and supporting code to support mutliple instances from 1 config...

```
<ezstream>
   <server>
       <stream>
             <media>
              </media>
       </stream> 
       <stream>
             <media>
              </media>
       </stream> 
       <stream>
             <media>
              </media>
       </stream> 
   </server>
</ezstream>
```

**Comment by mgrimm** [comment]
To answer the question, the answer is "no". You need to externally manage 3 instances of ezstream for this use case. Will keep this issue open for the time being, as it is close to what I have in mind for the future anyways. Thanks!

**Comment by mgrimm** [comment]
Closing; the 1.0.0 code base and configuration layout is prepared for this, but I can't commit to a time when this is implemented. It'll happen eventually.

**Comment by d47081** [comment]
So if I must to run separate PIDs for each stream, why folding / namespace `<streams><stream>` is for?
